# Compiler and flags
CXX := g++
CXXFLAGS := -g -Wall -std=c++17

# Include directories (project headers)
INCLUDES := -Isrc -Isrc/header

# Directories
SRCDIR := src
BUILDDIR := build

# Target executable
TARGET := main

SRCS := $(shell find $(SRCDIR) -name '*.cpp')

# Map sources to object files under build/
OBJS := $(patsubst $(SRCDIR)/%.cpp,$(BUILDDIR)/%.o,$(SRCS))

# Dependency files generated by -MMD
DEPS := $(OBJS:.o=.d)

.PHONY: all clean dirs run

all: dirs $(TARGET)

dirs:
	@mkdir -p $(BUILDDIR)

ifeq ($(strip $(SRCS)),)
$(error No .cpp files found in $(SRCDIR))
endif

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ $^

# Compile rule: produce .o and .d files
$(BUILDDIR)/%.o: $(SRCDIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -MMD -MP -c $< -o $@

# Include generated dependency files if present
-include $(DEPS)

clean:
	rm -rf $(BUILDDIR) $(TARGET)

run: all
	./$(TARGET)